Screenful.Loc={
  ready: "Ready.",
  filter: "Filter",
  removeFilter: "Clear filter",
  reload: "Reload",
  cancel: "Cancel",
  more: "More",
  new: "New",
  edit: "Edit",
  save: "Save",
  delete: "Delete",
  listing: "Getting list...",
  listingFailed: "Failed to get list.",
  reading: "Getting item...",
  readingFailed: "No such item.",
  saving: "Saving...",
  savingFailed: "Failed to save.",
  deleting: "Deleting...",
  deletingFailed: "Failed to delete.",
  deleteConfirm: "Careful now! Are you sure?",
  username: "E-mail address",
  password: "Password",
  login: "Log in",
  loginError: "Incorrect e-mail address or password.",
  logout: "Log out",
  anonymous: "anonymous user",
  home: "Home",
  title: "Title",
  titleEmpty: "The title should not be be empty.",
  url: "URL",
  urlEmpty: "The URL should not be be empty.",
  urlShort: "The URL should be at least three characters long.",
  urlInvalid: "The URL should not contain characters other than a-z, A-Z, 0-9 and hyphens.",
  urlTaken: "This URL is already taken.",
  template: "Template",
  create: "Create",
  finished: "Finished",
  changePwd: "Change your password",
  signup: "Get an account",
  forgotPwd: "Forgot your password?",
  signupEmail: "To get an account send an e-mail to",
  forgotPwdEmail: "If you have forgotten your password send an e-mail to",
  newPassword: "New password",
  change: "Change",
  passwordChanged: "Your password has been changed.",
  passwordEmpty: "The password should not be empty.",
  passwordShort: "The password should be at least six characters long.",
  passwordWhitespace: "The password should not begin or end with a space.",
  ok: "OK",
  currentUrl: "Current URL",
  newUrl: "New URL",
  upload: "Upload",
  uploadPurge: "Purge before upload",
  uploadFail: "The upload has failed.",
  uploadSuccess: "The upload has succeeded.",
  history: "History",
  version: "Version",
  clone: "Clone",
  sourceCode: "Source code",
  invalidSourceCode: "Invalid source code",
  unsavedConfirm: "You have unsaved changes. Are you sure you want to lose them?",
  doItLater: "Do it later",
};
