Screenful.Loc={
  ready: "Ready.",
  find: "Find",
  reload: "Reload",
  cancel: "Cancel",
  more: "More",
  new: "New",
  edit: "Edit",
  save: "Save",
  delete: "Delete",
  listing: "Getting list...",
  listingFailed: "Failed to get list.",
  reading: "Getting item...",
  readingFailed: "No such item.",
  saving: "Saving...",
  savingFailed: "Failed to save.",
  deleting: "Deleting...",
  deletingFailed: "Failed to delete.",
  deleteConfirm: "Careful now! Are you sure?",
  username: "E-mail address",
  password: "Password",
  login: "Log in",
  loginError: "Incorrect e-mail address or password.",
  logout: "Log out",
  anonymous: "anonymous user",
  home: "Home",
  title: "Title",
  titleEmpty: "The title should not be be empty.",
  url: "URL",
  urlEmpty: "The URL should not be be empty.",
  urlShort: "The URL should be at least three characters long.",
  urlInvalid: "The URL should not contain characters other than a-z, A-Z, 0-9 and hyphens.",
  urlTaken: "This URL is already taken.",
  template: "Template",
  create: "Create",
  finished: "Finished",
  changePwd: "Change your password",
  signup: "Get an account",
  forgotPwd: "Forgot your password?",
  signupEmail: "To get an account send an e-mail to",
  newPassword: "New password",
  change: "Change",
  passwordChanged: "Your password has been changed.",
  passwordEmpty: "The password should not be empty.",
  passwordShort: "The password should be at least six characters long.",
  passwordWhitespace: "The password should not begin or end with a space.",
  ok: "OK",
  currentUrl: "Current URL",
  newUrl: "New URL",
  upload: "Upload",
  uploadPurge: "Purge before upload",
  uploadFail: "The upload has failed.",
  uploadSuccess: "The upload has succeeded.",
  history: "History",
  version: "Version",
  clone: "Clone",
  sourceCode: "Source code",
  invalidSourceCode: "Invalid source code",
  unsavedConfirm: "You have unsaved changes. Are you sure you want to lose them?",
  doItLater: "Do it later",
  badEmailError: "Incorrect e-mail address.",

  forgotPwdEmail: "If you have forgotten your password, enter your e-mail address and we will send you instructions on how to create a new one.",
  recoverPwd: "Get a new password",
  tokenSent: "We have sent you an e-mail with instructions on how to reset your password.",
  recoverPwdMsg: "You can change your password now.",
  changePwdMsg: "You can change your password here.",
  invalidToken: "This password reset link is invalid. It may have expired or has been used before.",

  signupInfoEmail: "To get a new account, enter your e-mail address and we will send you instructions.",
  signupButton: "Create new account",
  signupTokenSent: "We have sent you an e-mail with instructions on how to create a new account.",
  invalidSignupToken: "This signup link is invalid. It may have expired or has been used before.",
  setPwdMsg: "Please set your password now.",
  accountCreated: "We have created your account. You can now log in with your e-mail address and password.",
  signupAccountExists: "You are trying to create an account for e-mail address that already has an account.",

  autosave: "Autosave",

  flagging: "Flagging...",
  flaggingFailed: "Failed to flag the entry.",

  exactMatches: "Exact matches",
  partialMatches: "Partial matches",

  termsTitle: "Terms of Use",
  termsOfUse: "Lexonomy is a service provided by <a href='https://www.lexicalcomputing.com' target='_blank'>Lexical Computing CZ s.r.o.</a>. This service is provided free of charge for <b>non-commercial purposes only</b>. Lexonomy is still in the development phase and no warranties are given as for service availability or fitness for particular purpose.<br/><br/>Commercial users as well as users interested in a guaranteed service level need to <a href='mailto:inquiries@sketchengine.eu'>contact us</a> in order to obtain a subscription.",
  termsConsent: "My usage is non-commercial and I agree to the terms of use",
  confirm: "Confirm",
  termsError: "Please, confirm Terms of Use before using Lexonomy.",
};
