Screenful.Loc={
  ready: "Réidh.",
  filter: "Scag",
  removeFilter: "Bain scagaire",
  reload: "Athlódáil",
  cancel: "Cealaigh",
  more: "Tuilleadh",
  new: "Nua",
  edit: "Athraigh",
  save: "Sábháil",
  delete: "Scrios",
  listing: "Liosta á fháil...",
  listingFailed: "Níor éirigh liom liosta a fháil.",
  reading: "Sonraí á fáil...",
  readingFailed: "Ní ann don iontráil.",
  saving: "Á shábháil...",
  savingFailed: "Níor éirigh liom na sonraí a shǎbháil.",
  deleting: "Á scrios...",
  deletingFailed: "Níor éirigh liom na sonraí a scrios.",
  deleteConfirm: "Cúramach anois! An bhfuil tú cinnte?",
  username: "Seoladh ríomhphoist",
  password: "Pasfhocal",
  login: "logáil isteach",
  loginError: "Seoladh ríomhphoist mícheart nó pasfhocal mícheart.",
  logout: "Logáil amach",
  anonymous: "úsáideoir anaithnid",
  home: "Baile",
  title: "Teideal",
  titleEmpty: "Ní cheadaítear an teideal a bheith folamh.",
  url: "URL",
  urlEmpty: "Ní cheadaítear an URL a bheith folamh.",
  urlShort: "Ba cheart trí charachtar, ar a laghad, a bheith sa URL.",
  urlInvalid: "Ní cheadaítear sa URL ach na carachtair a-z, A-Z, 0-9 agus fleiscín.",
  urlTaken: "Tá an URL seo in úsáid cheana.",
  template: "Teimpléad",
  create: "Cruthaigh",
  finished: "Críochnaithe",
  changePwd: "Athraigh do phasfhocal",
  signup: "Faigh cuntas duit féin",
  forgotPwd: "Pasfhocal dearmadta",
  signupEmail: "Chun cuntas a iarraidh, cuir ríomhphost chuig",
  forgotPwdEmail: "Má tá do phasfhocal dearmadta agat, cuir ríomhphost chuig",
  newPassword: "Pasfhocal nua",
  change: "Athraigh",
  passwordChanged: "Tá do phasfhocal athraithe.",
  passwordEmpty: "Ní cheadaítear an pasfhocal a bheith folamh.",
  passwordShort: "Ba cheart sé charachtar, ar a laghad, a bheith sa phasfhocal.",
  passwordWhitespace: "Ní cheart spás a bheith ag tús ná ag deireadh an phasfhocail.",
  ok: "OK",
  currentUrl: "URL reatha",
  newUrl: "URL nua",
  upload: "Uaslódáil",
  uploadPurge: "Folmhaigh roimh an uaslódáil",
  uploadFail: "Theip ar an uaslódáil.",
  uploadSuccess: "D'éirigh leis an uaslódáil.",
  history: "Stair",
  version: "Leagan",
  clone: "Clónáil",
  sourceCode: "Cód foinseach",
  invalidSourceCode: "Cód foinseach neamhbhailí",
};
