Screenful.Loc={
  ready: "Hotovo.",
  filter: "Filtrovat",
  removeFilter: "Odstranit filtr",
  reload: "Obnovit",
  cancel: "Storno",
  more: "Víc",
  new: "Nové",
  edit: "Upravit",
  save: "Uložit",
  delete: "Smazat",
  listing: "Čekáme na seznam ze serveru...",
  listingFailed: "Nepovedlo se získat seznam ze serveru.",
  reading: "Čekáme na data ze serveru...",
  readingFailed: "Neexistuje.",
  saving: "Ukládá se...",
  savingFailed: "Nepovedlo se to uložit.",
  deleting: "Maže se...",
  deletingFailed: "Nepovedlo se to smazat.",
  deleteConfirm: "Pozor s tímhle! Opravdu to chceš smazat?",
  username: "E-mailová adresa",
  password: "Heslo",
  login: "Přihlásit se",
  loginError: "Nesprávná e-mailová adresa nebo nesprávné heslo.",
  logout: "Odhlásit se",
  anonymous: "anonymní uživatel",
  home: "Domů",
  title: "Nadpis",
  titleEmpty: "Nadpis by neměl být prázdný.",
  url: "URL",
  urlEmpty: "URL by nemělo být prázdné.",
  urlShort: "URL by mělo být aspoň tři znaky dlouhé.",
  urlInvalid: "URL smí obsahovat jen znaky a-z, A-Z, 0-9 a pomlčku.",
  urlTaken: "Toto URL už je obsazené.",
  template: "Šablona",
  create: "Vytvořit",
  finished: "Hotovo",
  changePwd: "Změnit si heslo",
  signup: "Zřǐdit si účet",
  forgotPwd: "Zapomenuté heslo",
  signupEmail: "Chcete-li si nechat zřídit účet, napište e-mail na adresu",
  forgotPwdEmail: "Zapomněli-li jste své heslo, napište e-mail na adresu",
  newPassword: "Nové heslo",
  change: "Změnit",
  passwordChanged: "Vaše heslo bylo změněno.",
  passwordEmpty: "Heslo by nemělo být prazdné.",
  passwordShort: "Heslo by mělo být aspoň šest znaků dlouhé.",
  passwordWhitespace: "Heslo by nemělo začínat ani končit mezerou.",
  ok: "OK",
  currentUrl: "Současné URL",
  newUrl: "Nové URL",
  upload: "Nahrát",
  uploadPurge: "Před nahráním vyprázdnit.",
  uploadFail: "Nahrávání selhalo.",
  uploadSuccess: "Nahrávání se povedlo.",
  history: "Historie",
  version: "Verze",
  clone: "Klonovat",
  sourceCode: "Zdrojový kód",
  invalidSourceCode: "Neplatný zdrojový kód",
  unsavedConfirm: "Más neuložené změny. Opravdu o ně chceš přijít?",
};
