Screenful.Loc={
  ready: "Hotovo.",
  filter: "Filtrovat",
  removeFilter: "Odstranit filtr",
  reload: "Obnovit",
  cancel: "Storno",
  more: "Víc",
  new: "Nové",
  edit: "Upravit",
  save: "Uložit",
  delete: "Smazat",
  listing: "Čekáme na seznam ze serveru...",
  listingFailed: "Nepovedlo se získat seznam ze serveru.",
  reading: "Čekáme na data ze serveru...",
  readingFailed: "Neexistuje.",
  saving: "Ukládá se...",
  savingFailed: "Nepovedlo se to uložit.",
  deleting: "Maže se...",
  deletingFailed: "Nepovedlo se to smazat.",
  deleteConfirm: "Pozor s tímhle! Opravdu to chceš smazat?",
  username: "E-mailová adresa",
  password: "Heslo",
  login: "Přihlásit se",
  loginError: "Nesprávná e-mailová adresa nebo nesprávné heslo.",
  logout: "Odhlásit se",
  anonymous: "anonymní uživatel",
  home: "Domů",
  title: "Nadpis",
  titleEmpty: "Nadpis by neměl být prázdný.",
  url: "URL",
  urlEmpty: "URL by nemělo být prázdné.",
  urlShort: "URL by mělo být aspoň tři znaky dlouhé.",
  urlInvalid: "URL smí obsahovat jen znaky a-z, A-Z, 0-9 a pomlčku.",
  urlTaken: "Toto URL už je obsazené.",
  template: "Šablona",
  create: "Vytvořit",
  finished: "Hotovo",
  changePwd: "Změnit si heslo",
  signup: "Zřǐdit si účet",
  forgotPwd: "Zapomenuté heslo",
  signupEmail: "Chcete-li si nechat zřídit účet, napište e-mail na adresu",
  newPassword: "Nové heslo",
  change: "Změnit",
  passwordChanged: "Vaše heslo bylo změněno.",
  passwordEmpty: "Heslo by nemělo být prazdné.",
  passwordShort: "Heslo by mělo být aspoň šest znaků dlouhé.",
  passwordWhitespace: "Heslo by nemělo začínat ani končit mezerou.",
  ok: "OK",
  currentUrl: "Současné URL",
  newUrl: "Nové URL",
  upload: "Nahrát",
  uploadPurge: "Před nahráním vyprázdnit.",
  uploadFail: "Nahrávání selhalo.",
  uploadSuccess: "Nahrávání se povedlo.",
  history: "Historie",
  version: "Verze",
  clone: "Klonovat",
  sourceCode: "Zdrojový kód",
  invalidSourceCode: "Neplatný zdrojový kód",
  unsavedConfirm: "Más neuložené změny. Opravdu o ně chceš přijít?",
  doItLater: "Udělej to jindy",
  badEmailError: "Nesprávná e-mailová adresa.",

  forgotPwdEmail: "Zapomněli-li jste svoje heslo, zadejte tady svoji e-mailovou adresu a my vám pošleme instrukce, jak si získat nové heslo.",
  recoverPwd: "Chci nové heslo",
  tokenSent: "Poslali jsme vám instrukce, jak si získat nové heslo.",
  recoverPwdMsg: "Nyní si můžete změnit heslo.",
  changePwdMsg: "Tady si můžete změnit heslo.",
  invalidToken: "Tento odkaz je neplatný. Možná už vypršel, nebo byl už použit.",

  signupInfoEmail: "To get a new account, enter your e-mail address and we will send you instructions.",
  signupButton: "Create new account",
  signupTokenSent: "We have sent you an e-mail with instructions on how to create a new account.",
  invalidSignupToken: "This signup link is invalid. It may have expired or has been used before.",
  setPwdMsg: "Please set your password now.",
  accountCreated: "We have created your account. You can now log in with your e-mail address and password.",
  signupAccountExists: "You are trying to create an account for e-mail address that already has an account.",

  autosave: "Ukládat automaticky",

  flagging: "Flagging...",
  flaggingFailed: "Failed to flag the entry.",
};
