Screenful.Loc={
  ready: "Réidh.",
  find: "Aimsigh",
  reload: "Athlódáil",
  cancel: "Cealaigh",
  more: "Tuilleadh",
  new: "Nua",
  edit: "Athraigh",
  save: "Sábháil",
  delete: "Scrios",
  listing: "Liosta á fháil...",
  listingFailed: "Níor éirigh liom liosta a fháil.",
  reading: "Sonraí á bhfáil...",
  readingFailed: "Ní ann don iontráil.",
  saving: "Á shábháil...",
  savingFailed: "Níor éirigh liom na sonraí a shábháil.",
  deleting: "Á scrios...",
  deletingFailed: "Níor éirigh liom na sonraí a scrios.",
  deleteConfirm: "Cúramach anois! An bhfuil tú cinnte?",
  username: "Seoladh ríomhphoist",
  password: "Pasfhocal",
  login: "Logáil isteach",
  loginError: "Seoladh ríomhphoist mícheart nó pasfhocal mícheart.",
  logout: "Logáil amach",
  anonymous: "úsáideoir anaithnid",
  home: "Baile",
  title: "Teideal",
  titleEmpty: "Ní cheadaítear an teideal a bheith folamh.",
  url: "URL",
  urlEmpty: "Ní cheadaítear an URL a bheith folamh.",
  urlShort: "Ba cheart trí charachtar, ar a laghad, a bheith sa URL.",
  urlInvalid: "Ní cheadaítear sa URL ach na carachtair a-z, A-Z, 0-9 agus fleiscín.",
  urlTaken: "Tá an URL seo in úsáid cheana.",
  template: "Teimpléad",
  create: "Cruthaigh",
  finished: "Críochnaithe",
  changePwd: "Athraigh do phasfhocal",
  signup: "Faigh cuntas duit féin",
  forgotPwd: "Pasfhocal dearmadta",
  signupEmail: "Chun cuntas a iarraidh, cuir ríomhphost chuig",
  newPassword: "Pasfhocal nua",
  change: "Athraigh",
  passwordChanged: "Tá do phasfhocal athraithe.",
  passwordEmpty: "Ní cheadaítear an pasfhocal a bheith folamh.",
  passwordShort: "Ba cheart sé charachtar, ar a laghad, a bheith sa phasfhocal.",
  passwordWhitespace: "Ní cheart spás a bheith ag tús ná ag deireadh an phasfhocail.",
  ok: "OK",
  currentUrl: "URL reatha",
  newUrl: "URL nua",
  upload: "Uaslódáil",
  uploadPurge: "Folmhaigh roimh an uaslódáil",
  uploadFail: "Theip ar an uaslódáil.",
  uploadSuccess: "D'éirigh leis an uaslódáil.",
  history: "Stair",
  version: "Leagan",
  clone: "Clónáil",
  sourceCode: "Cód foinseach",
  invalidSourceCode: "Cód foinseach neamhbhailí",
  unsavedConfirm: "Tá athruithe déanta agat nach bhfuil sábháilte go fóill. An cuma leat go gcaillfear iad?",
  doItLater: "Déan níos déanaí é",
  badEmailError: "Seoladh ríomhphoist mícheart.",

  forgotPwdEmail: "Má tá do phasfhocal dearmadta agat, cuir do sheoladh ríomhphoist isteach anseo. Cuirfidh muidne treoracha chugat maidir leis an dóigh chun do phasfhocal a athrú.",
  recoverPwd: "Faigh pasfhocal nua",
  tokenSent: "Tá treoracha seolta againn chugat maidir leis an dóigh chun do phasfhocal a athrú.",
  recoverPwdMsg: "Is féidir leat do phasfhocal a athrú anois.",
  changePwdMsg: "Is féidir leat do phasfhocal a athrú anseo.",
  invalidToken: "Níl an nasc seo bailí. Seans go bhfuil sé imithe in éag, nó b'fhéidir gur baineadh úsáid as cheana.",

  signupInfoEmail: "To get a new account, enter your e-mail address and we will send you instructions.",
  signupButton: "Create new account",
  signupTokenSent: "We have sent you an e-mail with instructions on how to create a new account.",
  invalidSignupToken: "This signup link is invalid. It may have expired or has been used before.",
  setPwdMsg: "Please set your password now.",
  accountCreated: "We have created your account. You can now log in with your e-mail address and password.",
  signupAccountExists: "You are trying to create an account for e-mail address that already has an account.",

  autosave: "Sábháil uathoibríoch",

  flagging: "Flagging...",
  flaggingFailed: "Failed to flag the entry.",

  exactMatches: "Torthaí beachta",
  partialMatches: "Torthaí gaolmhara",
};
