import "./libs/screenful/screenful.css"
import "./libs/screenful/screenful-editor.css"
import "./libs/screenful/screenful-theme-blue.css"
import "./libs/screenful/screenful-history.css"
// import "./libs/xonomy/xonomy.css"
import "./widgets/ske.css"
import "./widgets/xrefs.css"
import "./widgets/xemplatron.css"
import "./widgets/kontext.css"
import "./widgets/sub.css"
import "./widgets/xema-designer.css"
import "./libs/materialize/css/materialize.min.css"
import "./libs/materialize/css/materialize-colorpicker.min.css"
import "./libs/jquery/css/jquery-ui.css"
import "./css/lexonomy.css"
