import './libs/riot/riot.min.js'
import './libs/riot/route.min.js'
import './libs/riot/observable.js'
import './libs/jquery/jquery.min.js'
import './libs/jquery/jquery-ui.min.js'
import './libs/materialize/materialize.min.js'
import './libs/materialize/materialize-colorpicker.min.js'
